### ISSUE TITLE
Add dynamically generated vocabularies to default vocabularies.json configuration file

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdKeywords#11]
Add dynamically generated and custom NGGDPP vocabularies to the default vocabulary configuration file ([vocabularies.json}(https://github.com/adiwg/mdKeywords/blob/master/resources/vocabularies.json).

The custom vocabularies for the USGS [National Geological and Geophysical Data Preservation Program](https://www.usgs.gov/programs/national-geological-and-geophysical-data-preservation-program) (NGGDPP) are being included in the default vocabulary configuration to assist USGS with a time sensitive need.

These, as well as the "LCC" vocabularies, will eventually need to be removed from the default when the custom vocabulary feature becomes fully functional and organizations have the ability to host them at other locations.

**Comment by jwaspin** [comment]
https://github.com/adiwg/mdKeywords/pull/9
That pull request added the new vocabularies but `vocabularies.json` should probably be reviewed for accuracy. If it's correct then this issue can probably be closed, but a new issue might be desired to revert this repository to default vocabularies only.

**Comment by jwaspin** [comment]
@hmaier-fws This is outdated, closing because what needs to be reviewed is now different.
