### ISSUE TITLE
Change default branch from dev to develop

### ISSUE THREAD

**Issue by hmaier-fws** [adiwg/mdKeywords#25]
@jwaspin The name change would make this consistent with the most other repos, which use develop as the default.

Any thoughts??

**Comment by jwaspin** [comment]
@hmaier-fws I was thinking the same thing. The more consistent we can be the better in my opinion. I think we just need to merge dev into master first, then we can branch the new develop off master and delete dev. Don't worry about the other branch I have going to remove npm module code, I can rebase that one to the develop branch and then open a PR for it.

**Comment by hmaier-fws** [comment]
closed by #26
